### PR TITLE
my soon to be favourite 3 movies

### PR DESCRIPTION
**Pull request by clam169**
@matteomiceli  Here are my soon to be 3 favourite movies.

### CODE REVIEW

**Review by matteomiceli — COMMENTED** [review]
@clam169 Hmm, there is a serious lack of the 2005 masterpiece Herby Fully Loaded

**Review by matteomiceli — CHANGES_REQUESTED** [review]
@clam169 Hmm, there is a serious lack of the 2005 masterpiece Herby Fully Loaded

**Comment by clam169** [comment]
You are totally right! Being loaded is awesome. Please review my updated list of movies.

**Review by matteomiceli — COMMENTED** [review]
Looks good @clam169!

**Pull request merged**
